### ISSUE TITLE
Questions about motion

### ISSUE THREAD

**Issue by ngpong** [svban/YankAssassin.nvim#1]
Hi @svban , great plugin! I'm a beginner with Neovim, and I've been exploring the possibilities of motion actions over the past few days. The demo in the README file piqued my interest. I want to clarify that this isn't a question directly related to the plugin itself. I understand this might be a bit of a bother, and I tried my best to search for any possible solutions before reaching out, but unfortunately, I failed.

To get to the point, I'm looking to understand the keystrokes you used in the three demo GIFs in the README, especially the second GIF. Here are a few points I'm curious about:

![2](https://user-images.githubusercontent.com/69670983/147871603-813e3248-a093-4915-b209-cad5da276aca.gif)

1. How did you select the content `cout << "lorem";` without moving the cursor?

3. Similarly, how did you select just `"lorem"` ?

5. I know about the `vi"` or `va"` key combinations, but they only seem to work on the current line if there are no surrounding delimiters. The key question is, how can I apply these motion to a specific line?

I hope you have a great day! Best wishes!

**Comment by svban** [comment]
Hey!!
1. This is the use case of [YankAssassin.nvim](https://github.com/svban/YankAssassin.nvim) itself. The exact commands I used are yinB

2. In vanilla neovim, you can only use text objects in the current line. I am not selecting, but rather yanking the text, its just the text highlight. I am using [mini.ai](https://github.com/echasnovski/mini.ai), the exact commands I used are yinq

3. All of it depends on the textobjects, mini.ai expands the text object functionality, so whenever you try to use any operator with any textobject, mini.ai will take care of that.

All I am using is YankAssassin.nvim - so that the cursor doesn't displace while yanking and Mini.ai for extended text object functionality.

Hope, this solves your queries
Cheers
